// Scans data/ and emits src/generated/verovio-data.ts (bundled text assets).
// Run: node scripts/embed-data.mjs
import { readdirSync, readFileSync, statSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const ROOT = process.cwd();
const DATA = join(ROOT, 'data');
const OUT = join(ROOT, 'src', 'generated', 'verovio-data.ts');

function walk(dir) {
  const out = [];
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else out.push(p);
  }
  return out;
}

const files = walk(DATA);
const bundle = {};
for (const f of files) {
  const key = relative(DATA, f).split(sep).join('/');
  bundle[key] = readFileSync(f, 'utf8');
}
mkdirSync(join(ROOT, 'src', 'generated'), { recursive: true });
const bytes = Buffer.byteLength(JSON.stringify(bundle), 'utf8');
writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/embed-data.mjs — do not edit.\n` +
    `// Embeds data/ (${files.length} files, ${(bytes / 1048576).toFixed(2)} MB raw) so the\n` +
    `// library runs in browsers with no fs. Regenerate after data/ changes.\n` +
    `export const VEROVIO_DATA: Record<string, string> = ${JSON.stringify(bundle)};\n`
);
console.log(`embedded ${files.length} files (${(bytes / 1048576).toFixed(2)} MB) -> src/generated/verovio-data.ts`);
