/** Bundled verovio data/ for browsers (no Node fs).
 *
 * `VEROVIO_DATA` is generated by scripts/embed-data.mjs. Lookup strips any
 * resource-dir prefix so the default path (/usr/local/share/verovio), the
 * Node candidates (data, src-cpp/data, ...) and browser served paths all hit
 * the same keys (e.g. `Bravura/E050.xml`, `text/Times.xml`, `footer.svg`).
 */
import { VEROVIO_DATA } from './generated/verovio-data';

function lookup(key: string): string | null {
  const hit: string | undefined = (VEROVIO_DATA as Record<string, string | undefined>)[key];
  return hit === undefined ? null : hit;
}

export function bundledReadText(path: string): string | null {
  const p = path.replace(/\\/g, '/');
  const direct = lookup(p);
  if (direct !== null) return direct;
  const dataIdx = p.lastIndexOf('data/');
  if (dataIdx >= 0) {
    const sub = lookup(p.slice(dataIdx + 5));
    if (sub !== null) return sub;
  }
  const parts = p.split('/');
  if (parts.length >= 2) {
    const tail = lookup(parts.slice(-2).join('/'));
    if (tail !== null) return tail;
  }
  return null;
}

export function hasBundledData(): boolean {
  return Object.keys(VEROVIO_DATA).length > 0;
}

export function bundledKeys(): string[] {
  return Object.keys(VEROVIO_DATA);
}
