/**
 * HumdrumInput::getLabelFromInstrumentCode table (iohumdrum.cpp 10029+).
 * Auto instrument-name lookup used when a spine has an `*I` code but no label.
 */
/** HumdrumInput::getLabelFromInstrumentCode table (iohumdrum.cpp). */
export const CODE_TO_LABEL: Record<string, string> = {
  'accor': "Accordion",
  'alto': "Alto",
  'anvil': "Anvil",
  'archl': "Archlute",
  'armon': "Harmonic",
  'arpa': "Harp",
  'bagpI': "Irish bagpipe",
  'bagpS': "Scottish bagpipe",
  'banjo': "Banjo",
  'bansu': "Bansuri",
  'barit': "Baritone",
  'mbari': "High baritone",
  'baset': "Bassett horn",
  'bass': "Bass",
  'bdrum': "Bass drum",
  'bongo': "Bongo",
  'bguit': "Bass guitar",
  'biwa': "Biwa",
  'bscan': "Singing bass",
  'bspro': "Basso profondo",
  'brush': "Brush",
  'calam': "Chalumeau",
  'calpe': "Calliope",
  'calto': "Contralto",
  'campn': "Bells",
  'cangl': "English horn",
  'canto': "Canto",
  'caril': "Carillon",
  'castr': "Castrato",
  'casts': "Castanets",
  'cbass': "Contrabass",
  'cello': "Violoncello",
  'cemba': "Harpsichord",
  'cetra': "Cittern",
  'chain': "Chain",
  'chime': "Tubular bells",
  'chcym': "China cymbal",
  'chlma': "Soprano shawm",
  'chlmt': "Tenor shawm",
  'clap': "Hand clap",
  'clara': "Alto Clarinet",
  'clarb': "Bass Clarinet",
  'claro': "Sopranino clarinet",
  'clarp': "Piccolo clarinet",
  'clars': "Clarinet",
  'clave': "Claves",
  'clavi': "Clavichord",
  'clest': "Celesta",
  'clrno': "Clarino",
  'colsp': "Coloratura soprano",
  'conga': "Conga",
  'cor': "Horn",
  'cornm': "Cornemuse",
  'corno': "Cornett",
  'cornt': "Cornet",
  'coro': "Chorus",
  'crshc': "Crash cymbal",
  'ctenor': "Contratenor",
  'ctina': "concertina",
  'drmsp': "Dramatic soprano",
  'drum': "Drum",
  'drumP': "Small drum",
  'dulc': "Dulcimer",
  'eguit': "Electric guitar",
  'fag_c': "Contrabassoon",
  'fagot': "Bassoon",
  'false': "Falsetto",
  'feme': "Female voice",
  'fife': "Fife",
  'fingc': "Finger Cymbals",
  'flex': "Flexatone",
  'flt': "Flute",
  'flt_a': "Alto flute",
  'flt_b': "Bass flute",
  'fltda': "Alto recorder",
  'fltdb': "Bass recorder",
  'fltdn': "Sopranino recorder",
  'fltds': "Soprano recorder",
  'fltdt': "Tenor recorder",
  'flugh': "Flugelhorn",
  'forte': "Fortepiano",
  'glock': "Glockenspiel",
  'gen': "Generic instrument",
  'genT': "Generic treble instrument",
  'genB': "Generic bass instrument",
  'gong': "Gong",
  'guitr': "Guitar",
  'hammd': "Hammond eletronic organ",
  'hbell': "Hand bells",
  'heck': "Heckelphone",
  'heltn': "Heroic tenor",
  'hichi': "Hichiriki",
  'hurdy': "Hurdy-gurdy",
  'kitv': "Kit violin",
  'klav': "Generic keyboard",
  'kokyu': "Kokyu",
  'komun': "Koumngo",
  'koto': "Koto",
  'kruma': "Alto crumhorn",
  'krumb': "Bass crumhorn",
  'krums': "Crumhorn",
  'krumt': "Tenor crumhorn",
  'lion': "Lion's roar",
  'liuto': "Lute",
  'lyrsp': "Lyric soprano",
  'lyrtn': "Lyric tenor",
  'male': "Male voice",
  'mando': "Mandolin",
  'marac': "Maracas",
  'marim': "Marimba",
  'mezzo': "Mezzo soprano",
  'nfant': "Child's voice",
  'nokan': "Nokan",
  'oboe': "Oboe",
  'oboeD': "Oboe d'amore",
  'ocari': "Ocarina",
  'ondes': "Ondes Martenot",
  'ophic': "Ophicleide",
  'organ': "Organ",
  'oud': "Oud",
  'panpi': "Panpipes",
  'paila': "Timbales",
  'pbell': "Bell plate",
  'pguit': "Portuguese guitar",
  'physh': "Physharmonica",
  'piano': "Piano",
  'piatt': "Cymbales",
  'picco': "Piccolo",
  'pipa': "Pipa",
  'piri': "Piri",
  'porta': "Portative organ",
  'psalt': "Psaltery",
  'qin': "Qin",
  'quinto': "Quinto",
  'quitr': "Gittern",
  'rackt': "Rackett",
  'ratch': "Ratchet",
  'ratl': "Rattle",
  'rebec': "Rebec",
  'recit': "Recitativo",
  'reedo': "Reed organ",
  'rhode': "Rhodes piano",
  'ridec': "Ride cymbal",
  'sarod': "Sarod",
  'sarus': "Sarrusophone",
  'saxA': "Alto saxophone",
  'saxB': "Bass saxophone",
  'saxN': "Sopranino saxophone",
  'saxR': "Baritone saxophone",
  'saxS': "Saxophone",
  'saxT': "Tenor saxophone",
  'sbell': "Sleigh bells",
  'sdrum': "Snare drum",
  'serp': "Serpent",
  'sesto': "Sesto",
  'shaku': "Shakuhachi",
  'shami': "Shamisen",
  'sheng': "Sheng",
  'sho': "Sho",
  'siren': "Siren",
  'sitar': "Sitar",
  'slap': "Slapstick",
  'soprn': "Soprano",
  'spshc': "Splash cymbal",
  'spok': "Spoken voice",
  'spokF': "Female spoken voice",
  'spokM': "Male spoken voice",
  'steel': "Steel drum",
  'stim': "Sprechstimme",
  'stimS': "Soprano Sprechstimme",
  'stimA': "Alto Sprechstimme",
  'stimC': "Contralto Sprechstimme",
  'stimR': "Baritone Sprechstimme",
  'stimB': "Bass Sprechstimme",
  'strdr': "String drum",
  'sxhA': "Alto saxhorn",
  'sxhB': "Bass saxhorn",
  'sxhC': "Contrabass saxhorn",
  'sxhR': "Baritons saxhorn",
  'sxhS': "Saxhorn",
  'sxhT': "Tenor saxhorn",
  'synth': "Synthesizer",
  'tabla': "Tabla",
  'tambn': "Tambourine",
  'tambu': "Tambura",
  'tambr': "Tambur",
  'tblok': "Temple blocks",
  'tdrum': "Tenor drum",
  'tenor': "Tenor",
  'timpa': "Timpani",
  'tiorb': "Theorbo",
  'tom': "Tom-tom",
  'trngl': "Triangle",
  'troma': "Alto trombone",
  'tromb': "Bass trombone",
  'tromp': "Trumpet",
  'tromP': "Piccolo trumpet",
  'tromB': "Bass trumpet",
  'tromt': "Trombone",
  'tuba': "Tuba",
  'tubaB': "Bass Tuba",
  'tubaC': "Contrabass Tuba",
  'tubaT': "Tenor Tuba",
  'tubaU': "Subcontrabass Tuba",
  'ukule': "Ukulele",
  'vibra': "Vibraphone",
  'vina': "Vina",
  'viola': "Viola",
  'violb': "Bass viola da gamba",
  'viold': "Viola d'amore",
  'viole': "violone",
  'violn': "Violin",
  'violp': "Piccolo violin",
  'viols': "Viola da gamba",
  'violt': "Tenor viola da gamba",
  'vox': "Voice",
  'wblok': "Woodblock",
  'xylo': "Xylophone",
  'zithr': "Zither",
  'zurna': "Zurna",
};
